name: PR

on:
  pull_request: {}

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:

    concurrency: ci_test
    outputs:
      semver: ${{steps.semver.outputs.version_tag}}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semver
        uses: paulhatch/semantic-version@v5.1.0
        with:
          bump_each_commit: true
        id: semver

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.2

      - name: Run Tests
        env:

        run: |
          go test -v ./...

      - name: Publish Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TAGGING_PAT }}
        with:
          tag_name: ${{ steps.semver.outputs.version_tag }}
          release_name: ${{ steps.semver.outputs.version_tag }}
          draft: false
          prerelease: false
