name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install gox
        run: go install github.com/mitchellh/gox@latest

      - name: Cross-compile (linux/windows/arm)
        run: |
          mkdir -p dist/
          gox -osarch="linux/amd64 linux/arm64 windows/amd64 windows/arm64" \
              -output "dist/bctool_{{.OS}}_{{.Arch}}" ./cmd

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/bctool_*
        env:
          GITHUB_TOKEN: ${{ secrets.TAGGING_PAT }}
