name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install gox
        run: go install github.com/mitchellh/gox@latest

      - name: Cross-compile with gox
        run: |
          mkdir -p dist/
          gox -osarch="linux/amd64 linux/arm64 windows/amd64 windows/arm64" \
            -output "dist/bctool_{{.OS}}_{{.Arch}}" .
          
          # Generate checksums
          cd dist
          for f in *; do
            shasum -a 256 "$f" > "$f.sha256"
          done


      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/bctool_*
            dist/*.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.TAGGING_PAT }}


  update-brew:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Homebrew tap
        uses: actions/checkout@v4
        with:
          repository: mselser95/homebrew-bctool
          token: ${{ secrets.TAGGING_PAT }}
          path: tap

      - name: Download checksums from release
        run: |
          curl -sL -o bctool_linux_amd64.sha256 https://github.com/mselser95/bctool/releases/download/${{ github.ref_name }}/bctool_linux_amd64.sha256
          curl -sL -o bctool_linux_arm64.sha256 https://github.com/mselser95/bctool/releases/download/${{ github.ref_name }}/bctool_linux_arm64.sha256

      - name: Parse SHA256 values
        id: sha
        run: |
          echo "linux_amd64=$(cut -d ' ' -f 1 bctool_linux_amd64.sha256)" >> $GITHUB_OUTPUT
          echo "linux_arm64=$(cut -d ' ' -f 1 bctool_linux_arm64.sha256)" >> $GITHUB_OUTPUT

      - name: Update Homebrew Formula
        run: |
          VERSION=${{ github.ref_name }}
          FORMULA=tap/Formula/bctool.rb

          cat <<EOF > $FORMULA
  class Bctool < Formula
  desc "Blockchain info tool"
  homepage "https://github.com/mselser95/bctool"
  version "${VERSION#v}"

  on_linux do
  if Hardware::CPU.intel?
  url "https://github.com/mselser95/bctool/releases/download/${VERSION}/bctool_linux_amd64"
  sha256 "${{ steps.sha.outputs.linux_amd64 }}"
  end
  
  if Hardware::CPU.arm?
  url "https://github.com/mselser95/bctool/releases/download/${VERSION}/bctool_linux_arm64"
  sha256 "${{ steps.sha.outputs.linux_arm64 }}"
  end
  end

  def install
  bin.install "#{stable.url.split('/')[-1]}" => "bctool"
  end

  test do
  system "#{bin}/bctool", "--help"
  end
  end
  EOF

- name: Commit and push updated formula
  run: |
    cd tap
    git config user.name "bctool bot"
    git config user.email "bctool@bot.com"
    git add Formula/bctool.rb
    git commit -m "Update bctool formula to ${{ github.ref_name }}"
    git push origin main